#pragma once

#include "nyx/union_bytes.h"

#include <map>
#include <ranges>
#include <string>
#include <string_view>
#include <unordered_map>

namespace nyx {

class Realm;
class IsolateData;

using BuiltinSourceMap = std::map<std::string, UnionBytes>;

// Builtin source registry
// In release builds, sources are embedded via js2c
// In debug builds, sources can be loaded from disk for hot-reload

class BuiltinLoader {
 public:
  BuiltinLoader();

  BuiltinLoader(const BuiltinLoader&) = delete;
  BuiltinLoader& operator=(const BuiltinLoader&) = delete;

  static void CreatePerIsolateProperties(IsolateData* isolate_data, v8::Local<v8::ObjectTemplate> target);
  static void CreatePerContextProperties(v8::Local<v8::Object> target, v8::Local<v8::Context> context);

  v8::MaybeLocal<v8::Function> LookupAndCompile(v8::Local<v8::Context> context, const char* id, Realm* optional_realm);
  v8::MaybeLocal<v8::Function> LookupAndCompile(v8::Local<v8::Context> context,
                                                const char* id,
                                                v8::LocalVector<v8::String>* parameters,
                                                Realm* optional_realm);

  v8::MaybeLocal<v8::Value> CompileAndCall(
      v8::Local<v8::Context> context, const char* id, int argc, v8::Local<v8::Value> argv[], Realm* optional_realm);
  v8::MaybeLocal<v8::Value> CompileAndCall(v8::Local<v8::Context> context, const char* id, Realm* realm);

  const BuiltinSourceMap& GetSourceMap() const { return source_; }
  [[nodiscard]] std::ranges::keys_view<std::ranges::ref_view<const BuiltinSourceMap>> GetBuiltinIds() const;

  // Set the lib directory path for disk-based loading
  void SetLibPath(const std::string& path);

  // Force reload from disk (development mode)
  void ReloadFromDisk();

  // Register external builtins (called during initialization)
  void RegisterExternalBuiltins();

 private:
  // Generated by js2c.cc in compiled_builtins.cc
  void LoadJavaScriptSource();

  v8::MaybeLocal<v8::String> LoadBuiltinSource(v8::Isolate* isolate, const char* id) const;
  v8::MaybeLocal<v8::Function> LookupAndCompileInternal(v8::Local<v8::Context> context,
                                                        const char* id,
                                                        v8::LocalVector<v8::String>* parameters,
                                                        Realm* optional_realm);

  static void BuiltinIdsGetter(v8::Local<v8::Name> property, const v8::PropertyCallbackInfo<v8::Value>& args);
  static void CompileFunction(const v8::FunctionCallbackInfo<v8::Value>& args);

  // Embedded sources (generated by js2c and loaded by LoadJavaScriptSource)
  BuiltinSourceMap source_;

  // Disk-loaded sources cache (for development)
  std::unordered_map<std::string, std::string> disk_sources_;

  // Path to lib directory
  std::string lib_path_;

  // Whether to prefer disk over embedded
  bool prefer_disk_ = false;
};

}  // namespace nyx
